name: Build Digital Butler PDF
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install deps
        run: pip install -r degitalbutler/degitalbutler_book/requirements.txt
      - name: Build PDF
        run: |
          cd degitalbutler/degitalbutler_book
          python scripts/make_book_pdf.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: digital_butler_book
          path: degitalbutler/degitalbutler_book/outputs/digital_butler_book.pdf
